name: carbon_footprint_app
description: Minimal Flutter app to call backend Carbon Footprint API
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  google_fonts: ^6.1.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1B5E20"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
